### ISSUE TITLE
Computed Property is not Firing

### ISSUE THREAD

**Issue by jrock2004** [adopted-ember-addons/ember-launch-darkly#217] opened 2020-09-26 01:46 UTC
So I started to play with this addon and when the page loads, I can see my flags and its working. I am trying to setup a computed property so when the flag changes, the computed property fires. Now I could be missing something.

When the page first loads I see the network call to LD and I see my flag. I click on a different route and then I click to come back. I see in the network tab that it calls LD again and I see the flag come back the value has changed. But my computed property does not re-fire.

/route/application.js

```js
model() {
  let user = {
    key: 'MyApp',
    custom: {
      LocationID: +locationId,
    },
  };

  return this.launchDarkly.initialize(user),
} 
```

/controller/mypage.js

```js
@computed('launchDarkly.sell-memberships')
get isSellMembership() {
  debugger;

  return this.launchDarkly.variation('sell-memberships');
}
```

/template/mypage.hbs

```hbs
{{#if this.isSellMembership}}
  <h1>True</h1>
{{else}}
  <h1>False</h1>
{{/if}}
```

I am sure I am missing something, but not sure what.

Update 1: I have added a debugger to the computed property and it never refires.

**Comment by achambers** [comment] 2020-10-27 11:15
Hi @jrock2004. Is this in local mode (https://github.com/adopted-ember-addons/ember-launch-darkly#local) or when running against the actual LD service? Or both?

**Comment by achambers** [comment] 2020-10-27 15:47
@jrock2004 Just had a little test of this scenario, using the local feature flags and it seems to work fine.

Do you have any code that's publicly accessible that reproduces what you're experiencing that I could have a look at?

**Comment by jrock2004** [comment] 2020-10-28 12:15
@achambers I am not running in local mode. the code I have is not public so not able to share.

**Comment by achambers** [comment] 2020-10-29 11:05
@jrock2004 Tricky to debug this without being able to see your code or reproduce it myself. Can you knock together a minimal reproduction (in a new repo or something) that we can use to investigate and verify?

**Comment by herzzanu** [comment] 2023-03-10 12:40
@jrock2004 I see this is an old issue. Do you still have the issue or can we close this?

**Comment by herzzanu** [comment] 2023-03-10 12:45
Closing since it's quite old. Feel free to reopen.

**Closed by herzzanu** 2023-03-10 12:45 UTC
